import keymirror from 'keymirror';

const actionTypes = keymirror({
  LOAD_AUTH_REQUEST: null,
  LOAD_AUTH_SUCCESS: null,
  LOAD_AUTH_FAILURE: null,
  LOG_IN_REQUEST: null,
  LOG_IN_SUCCESS: null,
  LOG_IN_FAILURE: null,
  SIGN_UP_REQUEST: null,
  SIGN_UP_SUCCESS: null,
  SIGN_UP_FAILURE: null,
  LOG_OUT_REQUEST: null,
  LOG_OUT_SUCCESS: null,
  LOG_OUT_FAILURE: null,
  ACTIVATE_CLUB_REQUEST: null,
  ACTIVATE_CLUB_SUCCESS: null,
  ACTIVATE_CLUB_FAILURE: null,
  CLEAR_ERROR: null,

  RESEND_EMAIL_REQUEST: null,
  RESEND_EMAIL_SUCCESS: null,
  RESEND_EMAIL_FAILURE: null,

  FETCH_CURRENT_PLAYERS_REQUEST: null,
  FETCH_CURRENT_PLAYERS_SUCCESS: null,
  FETCH_CURRENT_PLAYERS_FAILURE: null,

  ADD_PLAYER_REQUEST: null,
  UPDATE_PLAYER_REQUEST: null,
  DELETE_PLAYER_REQUEST: null,
  ADD_PLAYER_SUCCESS: null,
  UPDATE_PLAYER_SUCCESS: null,
  DELETE_PLAYER_SUCCESS: null,
  ADD_PLAYER_FAILURE: null,
  UPDATE_PLAYER_FAILURE: null,
  DELETE_PLAYER_FAILURE: null,
});

export default actionTypes;
